# Generated by Django 4.0.4 on 2022-06-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0003_user_avatar_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='user_avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='default-cover.jpg', upload_to='user_covers'),
        ),
    ]
