# Generated by Django 4.0.4 on 2022-06-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_types',
            new_name='notification_type',
        ),
    ]
