# Generated by Django 4.0.4 on 2022-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_notification_types_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Like'), ('F', 'Follow'), ('C', 'Comment'), ('CR', 'Comment_response'), ('LC', 'Like_comment')], default=None, max_length=2),
        ),
    ]
