# Generated by Django 4.0.4 on 2022-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ancestor_number',
            field=models.IntegerField(default=0),
        ),
    ]
